[2024-11-26T06:32:51.217+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-26T06:32:51.234+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-26T06:32:46.042415+00:00 [queued]>
[2024-11-26T06:32:51.244+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-26T06:32:46.042415+00:00 [queued]>
[2024-11-26T06:32:51.245+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-26T06:32:51.260+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_usa_spending_data_task> on 2024-11-26 06:32:46.042415+00:00
[2024-11-26T06:32:51.269+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=14204) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T06:32:51.271+0000] {standard_task_runner.py:72} INFO - Started process 14206 to run task
[2024-11-26T06:32:51.269+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_usa_spending', 'process_usa_spending_data_task', 'manual__2024-11-26T06:32:46.042415+00:00', '--job-id', '387', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpw24qujgm']
[2024-11-26T06:32:51.271+0000] {standard_task_runner.py:105} INFO - Job 387: Subtask process_usa_spending_data_task
[2024-11-26T06:32:51.320+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-26T06:32:46.042415+00:00 [running]> on host 6a246d8d590f
[2024-11-26T06:32:51.646+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_usa_spending' AIRFLOW_CTX_TASK_ID='process_usa_spending_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T06:32:46.042415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T06:32:46.042415+00:00'
[2024-11-26T06:32:51.647+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-26T06:32:52.036+0000] {logging_mixin.py:190} INFO - Processing file: funding_data_11_26_2024.csv
[2024-11-26T06:32:52.553+0000] {logging_mixin.py:190} INFO - Processing file: other_data_11_26_2024.csv
[2024-11-26T06:32:52.873+0000] {logging_mixin.py:190} INFO - Processing file: spending_by_award_11_26_2024.csv
[2024-11-26T06:32:53.219+0000] {logging_mixin.py:190} INFO - Processing file: subawards_11_26_2024.csv
[2024-11-26T06:32:53.220+0000] {logging_mixin.py:190} INFO - Processing file: transactions_11_26_2024.csv
[2024-11-26T06:32:53.579+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_processing/usa_spending_processing_script.py", line 490, in process_usa_spending_data
    recipients_df = get_recipients_data(awards_df,sub_awards_df)
                                                  ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'sub_awards_df' where it is not associated with a value
[2024-11-26T06:32:53.596+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ETL_usa_spending, task_id=process_usa_spending_data_task, run_id=manual__2024-11-26T06:32:46.042415+00:00, execution_date=20241126T063246, start_date=20241126T063251, end_date=20241126T063253
[2024-11-26T06:32:53.612+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-26T06:32:53.613+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 387 for task process_usa_spending_data_task (cannot access local variable 'sub_awards_df' where it is not associated with a value; 14206)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_processing/usa_spending_processing_script.py", line 490, in process_usa_spending_data
    recipients_df = get_recipients_data(awards_df,sub_awards_df)
                                                  ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'sub_awards_df' where it is not associated with a value
[2024-11-26T06:32:53.654+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-26T06:32:53.678+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T06:32:53.683+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
