[2024-11-24T03:35:30.240+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T03:35:30.307+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T03:35:30.345+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T03:35:30.347+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-24T03:35:30.411+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_usa_spending_data_task> on 2024-11-23 00:00:00+00:00
[2024-11-24T03:35:30.450+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=95808) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-24T03:35:30.456+0000] {standard_task_runner.py:72} INFO - Started process 95816 to run task
[2024-11-24T03:35:30.451+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_usa_spending', 'process_usa_spending_data_task', 'scheduled__2024-11-23T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpmiqm3iwu']
[2024-11-24T03:35:30.461+0000] {standard_task_runner.py:105} INFO - Job 216: Subtask process_usa_spending_data_task
[2024-11-24T03:35:30.644+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_usa_spending.process_usa_spending_data_task scheduled__2024-11-23T00:00:00+00:00 [running]> on host 7da4b16cbed4
[2024-11-24T03:35:31.163+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_usa_spending' AIRFLOW_CTX_TASK_ID='process_usa_spending_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T00:00:00+00:00'
[2024-11-24T03:35:31.174+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T03:35:33.594+0000] {logging_mixin.py:190} INFO - Processing file: award_data_11_23_2024.csv
[2024-11-24T03:35:33.598+0000] {logging_mixin.py:190} INFO - Processing file: df_spending_by_award_11_23_2024.csv
[2024-11-24T03:35:34.211+0000] {logging_mixin.py:190} INFO - Processing file: funding_data_11_23_2024.csv
[2024-11-24T03:35:35.063+0000] {logging_mixin.py:190} INFO - Processing file: funding_data_11_24_2024.csv
[2024-11-24T03:35:35.922+0000] {logging_mixin.py:190} INFO - Processing file: other_data_11_23_2024.csv
[2024-11-24T03:35:36.296+0000] {logging_mixin.py:190} INFO - Processing file: other_data_11_24_2024.csv
[2024-11-24T03:35:36.699+0000] {logging_mixin.py:190} INFO - Processing file: spending_by_award_11_23_2024.csv
[2024-11-24T03:35:37.194+0000] {logging_mixin.py:190} INFO - Processing file: spending_by_award_11_24_2024.csv
[2024-11-24T03:35:37.729+0000] {logging_mixin.py:190} INFO - Processing file: subawards_11_23_2024.csv
[2024-11-24T03:35:37.732+0000] {logging_mixin.py:190} INFO - Processing file: subawards_11_24_2024.csv
[2024-11-24T03:35:37.735+0000] {logging_mixin.py:190} INFO - Processing file: transactions_11_23_2024.csv
[2024-11-24T03:35:38.296+0000] {logging_mixin.py:190} INFO - Processing file: transactions_11_24_2024.csv
[2024-11-24T03:35:38.813+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_processing/usa_spending_processing_script.py", line 482, in process_usa_spending_data
    states_df = get_states_data(other_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_processing/usa_spending_processing_script.py", line 23, in get_states_data
    grants_df[["recipient_state_name", "recipient_state_code"]]
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['recipient_state_name', 'recipient_state_code'], dtype='object')] are in the [columns]"
[2024-11-24T03:35:38.922+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ETL_usa_spending, task_id=process_usa_spending_data_task, run_id=scheduled__2024-11-23T00:00:00+00:00, execution_date=20241123T000000, start_date=20241124T033530, end_date=20241124T033538
[2024-11-24T03:35:38.979+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T03:35:38.983+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 216 for task process_usa_spending_data_task ("None of [Index(['recipient_state_name', 'recipient_state_code'], dtype='object')] are in the [columns]"; 95816)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_processing/usa_spending_processing_script.py", line 482, in process_usa_spending_data
    states_df = get_states_data(other_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_processing/usa_spending_processing_script.py", line 23, in get_states_data
    grants_df[["recipient_state_name", "recipient_state_code"]]
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['recipient_state_name', 'recipient_state_code'], dtype='object')] are in the [columns]"
[2024-11-24T03:35:39.067+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-24T03:35:39.144+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T03:35:39.165+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
