[2024-11-11T20:24:11.995+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-11T20:24:12.048+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_performance_reports.process_performance_reports_task manual__2024-11-11T20:24:09.612426+00:00 [queued]>
[2024-11-11T20:24:12.100+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_performance_reports.process_performance_reports_task manual__2024-11-11T20:24:09.612426+00:00 [queued]>
[2024-11-11T20:24:12.101+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-11T20:24:12.164+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_performance_reports_task> on 2024-11-11 20:24:09.612426+00:00
[2024-11-11T20:24:12.204+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1691) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-11T20:24:12.200+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'process_performance_reports', 'process_performance_reports_task', 'manual__2024-11-11T20:24:09.612426+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmphyozpgl_']
[2024-11-11T20:24:12.215+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask process_performance_reports_task
[2024-11-11T20:24:12.206+0000] {standard_task_runner.py:72} INFO - Started process 1693 to run task
[2024-11-11T20:24:12.357+0000] {task_command.py:467} INFO - Running <TaskInstance: process_performance_reports.process_performance_reports_task manual__2024-11-11T20:24:09.612426+00:00 [running]> on host ecd316daaa34
[2024-11-11T20:24:12.650+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_performance_reports' AIRFLOW_CTX_TASK_ID='process_performance_reports_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T20:24:09.612426+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T20:24:09.612426+00:00'
[2024-11-11T20:24:12.654+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-11T20:24:12.973+0000] {logging_mixin.py:190} INFO - Processing file: source-5_page-11.pdf
[2024-11-11T20:24:18.775+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/scripts/quarterly_performance_reports_extraction_script.py:123 FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-11-11T20:24:18.778+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/scripts/quarterly_performance_reports_extraction_script.py:124 FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-11-11T20:24:18.780+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/scripts/quarterly_performance_reports_extraction_script.py:125 FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-11-11T20:24:22.996+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/quarterly_performance_reports_extraction_script.py", line 356, in process_performance_reports
    save_to_s3(performance_reports_df, destination_bucket_name, f'{destination_folder}/performance_reports.csv')
  File "/opt/airflow/dags/scripts/quarterly_performance_reports_extraction_script.py", line 281, in save_to_s3
    s3_resource.Object(bucket_name, output_file_key).put(Body=csv_buffer.getvalue())
    ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 922, in __getattr__
    raise AttributeError(
AttributeError: 'S3' object has no attribute 'Object'
[2024-11-11T20:24:23.031+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=process_performance_reports, task_id=process_performance_reports_task, run_id=manual__2024-11-11T20:24:09.612426+00:00, execution_date=20241111T202409, start_date=20241111T202412, end_date=20241111T202423
[2024-11-11T20:24:23.055+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-11T20:24:23.058+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task process_performance_reports_task ('S3' object has no attribute 'Object'; 1693)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/quarterly_performance_reports_extraction_script.py", line 356, in process_performance_reports
    save_to_s3(performance_reports_df, destination_bucket_name, f'{destination_folder}/performance_reports.csv')
  File "/opt/airflow/dags/scripts/quarterly_performance_reports_extraction_script.py", line 281, in save_to_s3
    s3_resource.Object(bucket_name, output_file_key).put(Body=csv_buffer.getvalue())
    ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 922, in __getattr__
    raise AttributeError(
AttributeError: 'S3' object has no attribute 'Object'
[2024-11-11T20:24:23.085+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-11T20:24:23.102+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-11T20:24:23.105+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
