[2024-11-29T00:00:12.300+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-29T00:00:12.378+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_quarterly_performance_reports.process_performance_reports_task scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T00:00:12.417+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_quarterly_performance_reports.process_performance_reports_task scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T00:00:12.419+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-29T00:00:12.490+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_performance_reports_task> on 2024-11-28 00:00:00+00:00
[2024-11-29T00:00:12.553+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=43722) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T00:00:12.567+0000] {standard_task_runner.py:72} INFO - Started process 43739 to run task
[2024-11-29T00:00:12.552+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_quarterly_performance_reports', 'process_performance_reports_task', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '455', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmp7obnr623']
[2024-11-29T00:00:12.571+0000] {standard_task_runner.py:105} INFO - Job 455: Subtask process_performance_reports_task
[2024-11-29T00:00:12.844+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_quarterly_performance_reports.process_performance_reports_task scheduled__2024-11-28T00:00:00+00:00 [running]> on host 6a246d8d590f
[2024-11-29T00:00:14.827+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_quarterly_performance_reports' AIRFLOW_CTX_TASK_ID='process_performance_reports_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T00:00:00+00:00'
[2024-11-29T00:00:14.837+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-29T00:00:36.328+0000] {logging_mixin.py:190} INFO - Error while fetching data from PostgreSQL connection to server at "database-1.cfwk0mcqm9mf.us-east-2.rds.amazonaws.com" (18.218.251.218), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-29T00:00:36.331+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_processing/quarterly_performance_reports_processing_script.py", line 288, in process_performance_reports
    activity_id = get_max_value(table_name='activities',column_name='activity_id')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helpers/db_utils.py", line 104, in get_max_value
    cursor.close()
    ^^^^^^
UnboundLocalError: cannot access local variable 'cursor' where it is not associated with a value
[2024-11-29T00:00:36.424+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ETL_quarterly_performance_reports, task_id=process_performance_reports_task, run_id=scheduled__2024-11-28T00:00:00+00:00, execution_date=20241128T000000, start_date=20241129T000012, end_date=20241129T000036
[2024-11-29T00:00:36.482+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-29T00:00:36.484+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 455 for task process_performance_reports_task (cannot access local variable 'cursor' where it is not associated with a value; 43739)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_processing/quarterly_performance_reports_processing_script.py", line 288, in process_performance_reports
    activity_id = get_max_value(table_name='activities',column_name='activity_id')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helpers/db_utils.py", line 104, in get_max_value
    cursor.close()
    ^^^^^^
UnboundLocalError: cannot access local variable 'cursor' where it is not associated with a value
[2024-11-29T00:00:36.589+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-29T00:00:36.622+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
