[2024-11-22T05:16:33.055+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T05:16:33.109+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-22T05:16:24.434460+00:00 [queued]>
[2024-11-22T05:16:33.145+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-22T05:16:24.434460+00:00 [queued]>
[2024-11-22T05:16:33.147+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-22T05:16:33.221+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_usa_spending_data_task> on 2024-11-22 05:16:24.434460+00:00
[2024-11-22T05:16:33.268+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_usa_spending', 'process_usa_spending_data_task', 'manual__2024-11-22T05:16:24.434460+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpc3mp1hgy']
[2024-11-22T05:16:33.269+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=70981) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T05:16:33.273+0000] {standard_task_runner.py:105} INFO - Job 162: Subtask process_usa_spending_data_task
[2024-11-22T05:16:33.277+0000] {standard_task_runner.py:72} INFO - Started process 70989 to run task
[2024-11-22T05:16:33.350+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-22T05:16:24.434460+00:00 [running]> on host 7da4b16cbed4
[2024-11-22T05:16:33.508+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_usa_spending' AIRFLOW_CTX_TASK_ID='process_usa_spending_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T05:16:24.434460+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T05:16:24.434460+00:00'
[2024-11-22T05:16:33.511+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T05:16:34.426+0000] {logging_mixin.py:190} INFO - Processing file: df_spending_by_award_11_17_2024.csv
[2024-11-22T05:16:34.792+0000] {logging_mixin.py:190} INFO - Processing file: federal_account_funding_df_2024-11-17.csv
[2024-11-22T05:16:35.411+0000] {logging_mixin.py:190} INFO - Processing file: other_variables_11_17_2024.csv
[2024-11-22T05:16:35.726+0000] {logging_mixin.py:190} INFO - Processing file: sub_award_df_2024-11-17.csv
[2024-11-22T05:16:36.059+0000] {logging_mixin.py:190} INFO - Processing file: transactions_df_2024-11-17.csv
[2024-11-22T05:16:38.900+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 448, in process_usa_spending_data
    federal_awards_df = get_federal_awards_data(awards_df, sub_agency_df)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 307, in get_federal_awards_data
    sub_agency_df[["awarding_sub_agency_name", "awarding_sub_agency_code"]].rename(
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['awarding_sub_agency_name', 'awarding_sub_agency_code'], dtype='object')] are in the [columns]"
[2024-11-22T05:16:38.979+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ETL_usa_spending, task_id=process_usa_spending_data_task, run_id=manual__2024-11-22T05:16:24.434460+00:00, execution_date=20241122T051624, start_date=20241122T051633, end_date=20241122T051638
[2024-11-22T05:16:39.047+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T05:16:39.050+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 162 for task process_usa_spending_data_task ("None of [Index(['awarding_sub_agency_name', 'awarding_sub_agency_code'], dtype='object')] are in the [columns]"; 70989)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 448, in process_usa_spending_data
    federal_awards_df = get_federal_awards_data(awards_df, sub_agency_df)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 307, in get_federal_awards_data
    sub_agency_df[["awarding_sub_agency_name", "awarding_sub_agency_code"]].rename(
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['awarding_sub_agency_name', 'awarding_sub_agency_code'], dtype='object')] are in the [columns]"
[2024-11-22T05:16:39.120+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T05:16:39.159+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T05:16:39.162+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
